### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by remkolems** [budimanjojo/talhelper#255]
Version info
```
talhelper version 1.16.1 (installed via brew)
Ubuntu 22.04.3 LTS (bare metal)
```

Entered within command line environment (one or the other does not matter):
`talhelper genconfig --env-file talenv.sops.yaml --secret-file talsecret.sops.yaml --config-file talconfig.yaml`
or 
`talhelper genconfig`

Results in (unfortunately):
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xed39a3]

goroutine 1 [running]:
github.com/budimanjojo/talhelper/pkg/talos.applyNodeOverride(0xc0001409a0, {0x1374bf8, 0xc00048bb40})
        github.com/budimanjojo/talhelper/pkg/talos/nodeconfig.go:99 +0x423
github.com/budimanjojo/talhelper/pkg/talos.GenerateNodeConfig(0xc0001409a0, 0xc000130a80, 0xc00048c3f0?, 0x2f?)
        github.com/budimanjojo/talhelper/pkg/talos/nodeconfig.go:44 +0x134
github.com/budimanjojo/talhelper/pkg/talos.GenerateNodeConfigBytes(0xc0001a0c00?, 0x11baffe?, 0x13?, 0x6c?)
        github.com/budimanjojo/talhelper/pkg/talos/nodeconfig.go:15 +0x13
github.com/budimanjojo/talhelper/pkg/generate.GenerateConfig(0xc0001a0c00, 0x0, {0x11baffe, 0xf}, {0xc000158198?, 0x0?}, {0x11aefb0, 0x5}, 0x0?)
        github.com/budimanjojo/talhelper/pkg/generate/config.go:32 +0x31e
github.com/budimanjojo/talhelper/cmd.glob..func5(0xc00019ca00?, {0xc000114600?, 0x4?, 0x11ae663?})
        github.com/budimanjojo/talhelper/cmd/genconfig.go:46 +0x22c
github.com/spf13/cobra.(*Command).execute(0x1b65900, {0xc0001145a0, 0x6, 0x6})
        github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x1b66a40)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/budimanjojo/talhelper/cmd.Execute(...)
        github.com/budimanjojo/talhelper/cmd/root.go:53
main.main()
        github.com/budimanjojo/talhelper/main.go:10 +0x1b
```

**Comment by budimanjojo** [comment]
Thanks for the report @remkolems! Can you also provide your talconfig.yaml?

**Comment by budimanjojo** [comment]
@remkolems Hello, thanks for reporting. It was caused by missing `schematic` field, should be fixed in the latest patch release. Please try it out and report back here if you still have the same panic.
