### ISSUE TITLE
Supplying an empty file as patch panic the program

### ISSUE THREAD

**Issue by budimanjojo** [budimanjojo/talhelper#413]
Looks like this PR https://github.com/budimanjojo/talhelper/pull/397 caused a strange problem with supplying empty file as patch, thanks for the report by @cschmittiey on Discord.
Something like this:
```
patches:
  - "@./this-file-is-empty.yaml"
```
where `this-file-is-empty.yaml` is an empty file cause this error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe05631]

goroutine 1 [running]:
github.com/budimanjojo/talhelper/pkg/decrypt.(*sopsFile).isEncrypted(...)
        /home/budiman/Github/talhelper/pkg/decrypt/decrypt.go:53
github.com/budimanjojo/talhelper/pkg/decrypt.DecryptYamlWithSops({0xc000661721, 0xc})
        /home/budiman/Github/talhelper/pkg/decrypt/decrypt.go:39 +0x91
github.com/budimanjojo/talhelper/pkg/patcher.PatchesPatcher({0xc0003af500?, 0x1448fd0?, 0x1d80860?}, {0xc000550000, 0x71df, 0x8000})
        /home/budiman/Github/talhelper/pkg/patcher/patcher.go:59 +0x168
github.com/budimanjojo/talhelper/pkg/generate.GenerateConfig(0xc000004388, 0x0, {0x127d193, 0xf}, {0x127bf95?, 0x1c?}, {0x1270af9, 0x5}, 0x
1)
        /home/budiman/Github/talhelper/pkg/generate/config.go:41 +0x425
github.com/budimanjojo/talhelper/cmd.init.func7(0xc000255100?, {0xc000080580?, 0x4?, 0x1270176?})
        /home/budiman/Github/talhelper/cmd/genconfig.go:50 +0x2e9
github.com/spf13/cobra.(*Command).execute(0x1d0c1a0, {0xc000080560, 0x1, 0x1})
        /home/budiman/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x1d0d2e0)
        /home/budiman/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/budiman/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/budimanjojo/talhelper/cmd.Execute(...)
        /home/budiman/Github/talhelper/cmd/root.go:61
main.main()
        /home/budiman/Github/talhelper/main.go:10 +0x1b
exit status 2
```

**Comment by cschmittiey** [comment]
<img width="1178" alt="Screenshot 2024-04-14 at 2 04 28 PM" src="https://github.com/budimanjojo/talhelper/assets/7754798/f43aa76d-42b6-43fb-b96b-082eeca10a36">
Tested and works with my config. thanks again
